### ISSUE TITLE
CachedDataAccessController.getSpectrumById()  ClassCastException

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Utilities/ms-data-core-api#12]
In class: CachedDataAccessController

L166
```java
Spectrum getSpectrumById(Comparable id, boolean useCache) {
    return useCache ? (Spectrum) cache.get(CacheEntry.SPECTRUM, id) : null;
}
```

This method is being used by the PX submission pipeline:
```java
Spectrum spectrum = dataAccessController.getSpectrumById(specId);
```

>java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to uk.ac.ebi.pride.utilities.data.core.Spectrum

So the cache.get() is returning a SynchonizedMap<Spectrum> instead of just one Spectrum object.

Tobias

**Comment by Tobias-Ternent** [comment]
```
java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to uk.ac.ebi.pride.utilities.data.core.Spectrum
        at uk.ac.ebi.pride.utilities.data.controller.impl.ControllerImpl.CachedDataAccessController.getSpectrumById(CachedDataAccessController.java:166) ~[ms-data-core-api-2.0.6-SNAPSHOT.jar:na]
        at uk.ac.ebi.pride.utilities.data.controller.impl.ControllerImpl.ReferencedIdentificationController.getSpectrumById(ReferencedIdentificationController.java:407) ~[ms-data-core-api-2.0.6-SNAPSHOT.jar:na]
        at uk.ac.ebi.pride.utilities.data.controller.impl.ControllerImpl.CachedDataAccessController.getSpectrumById(CachedDataAccessController.java:154) ~[ms-data-core-api-2.0.6-SNAPSHOT.jar:na]
        at uk.ac.ebi.pride.submission.AssayFileScanner.scanEntryByEntry(AssayFileScanner.java:409) ~[submission-pipeline-2.0.0.jar:na]
        at uk.ac.ebi.pride.submission.AssayFileScanner.scan(AssayFileScanner.java:90) ~[submission-pipeline-2.0.0.jar:na]

```

**Comment by ypriverol** [comment]
Should be address in the performance optimization.
